using System;
using System.Collections.Generic;
using ScrewsMaster;
using Spine.Unity;
using Unity.VisualScripting;
using UnityEngine;

public class CreatSheepCard : MonoBehaviour
{

    public static CreatSheepCard instance;
    private List<Sprite> img_list;

    public Camera orthoCamera; // 这个变量应该被设置为您想要调整大小的正交相机


    private void Awake()
    {
        instance = this;
        orthoCamera = GameObject.Find("Camera1").GetComponent<Camera>();

        orthoCamera.orthographicSize = (float)Math.Round(28.125f / ((float)Screen.width / Screen.height), 4);

    }
    
}
